// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {utils} from '../models';
import {internal} from '../models';

export function CheckBugReportAPI():Promise<boolean>;

export function CheckIsDefaultEMLHandler():Promise<boolean>;

export function ConvertToUTF8(arg1:string):Promise<string>;

export function CreateBugReportFolder():Promise<main.BugReportResult>;

export function DetectEmailFormat(arg1:string):Promise<string>;

export function ExportSettings(arg1:string):Promise<string>;

export function FrontendLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetConfig():Promise<utils.Config>;

export function GetCurrentMailFilePath():Promise<string>;

export function GetExportAttachmentFolder():Promise<string>;

export function GetImageViewerData():Promise<main.ImageViewerData>;

export function GetLogsDir():Promise<string>;

export function GetMachineData():Promise<utils.MachineInfo>;

export function GetPDFViewerData():Promise<main.PDFViewerData>;

export function GetStartupFile():Promise<string>;

export function GetViewerData():Promise<main.ViewerData>;

export function ImportSettings():Promise<string>;

export function IsAppInDebugMode():Promise<boolean>;

export function IsDebuggerRunning():Promise<boolean>;

export function OpenDefaultAppsSettings():Promise<void>;

export function OpenDocument(arg1:string,arg2:string):Promise<void>;

export function OpenEMLWindow(arg1:string,arg2:string):Promise<void>;

export function OpenExplorerForPath(arg1:string):Promise<void>;

export function OpenFolderInExplorer(arg1:string):Promise<void>;

export function OpenImage(arg1:string,arg2:string):Promise<void>;

export function OpenImageWindow(arg1:string,arg2:string):Promise<void>;

export function OpenPDF(arg1:string,arg2:string):Promise<void>;

export function OpenPDFWindow(arg1:string,arg2:string):Promise<void>;

export function OpenURLInBrowser(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function ReadAuto(arg1:string):Promise<internal.EmailData>;

export function ReadEML(arg1:string):Promise<internal.EmailData>;

export function ReadMSG(arg1:string):Promise<internal.EmailData>;

export function ReadPEC(arg1:string):Promise<internal.EmailData>;

export function ReloadConfig():Promise<utils.Config>;

export function ReloadEMLyConfig():Promise<utils.EMLyConfig>;

export function RestartApp():Promise<void>;

export function SaveAttachment(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:utils.Config):Promise<void>;

export function SaveScreenshot():Promise<string>;

export function SaveScreenshotAs():Promise<string>;

export function SetCurrentMailFilePath(arg1:string):Promise<void>;

export function SetExportAttachmentFolder(arg1:string):Promise<void>;

export function ShowOpenFileDialog():Promise<string>;

export function ShowOpenFolderDialog():Promise<string>;

export function SubmitBugReport(arg1:main.BugReportInput,arg2:string):Promise<main.SubmitBugReportResult>;

export function TakeScreenshot():Promise<main.ScreenshotResult>;
