// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {main} from '../models';
import {internal} from '../models';

export function CheckIsDefaultEMLHandler():Promise<boolean>;

export function GetConfig():Promise<utils.Config>;

export function GetImageViewerData():Promise<main.ImageViewerData>;

export function GetMachineData():Promise<utils.MachineInfo>;

export function GetPDFViewerData():Promise<main.PDFViewerData>;

export function GetStartupFile():Promise<string>;

export function GetViewerData():Promise<main.ViewerData>;

export function OpenDefaultAppsSettings():Promise<void>;

export function OpenImage(arg1:string,arg2:string):Promise<void>;

export function OpenImageWindow(arg1:string,arg2:string):Promise<void>;

export function OpenPDF(arg1:string,arg2:string):Promise<void>;

export function OpenPDFWindow(arg1:string,arg2:string):Promise<void>;

export function QuitApp():Promise<void>;

export function ReadEML(arg1:string):Promise<internal.EmailData>;

export function SaveConfig(arg1:utils.Config):Promise<void>;

export function ShowOpenFileDialog():Promise<string>;
