// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIsDefaultEMLHandler() {
  return window['go']['main']['App']['CheckIsDefaultEMLHandler']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetImageViewerData() {
  return window['go']['main']['App']['GetImageViewerData']();
}

export function GetMachineData() {
  return window['go']['main']['App']['GetMachineData']();
}

export function GetPDFViewerData() {
  return window['go']['main']['App']['GetPDFViewerData']();
}

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function GetViewerData() {
  return window['go']['main']['App']['GetViewerData']();
}

export function OpenDefaultAppsSettings() {
  return window['go']['main']['App']['OpenDefaultAppsSettings']();
}

export function OpenEMLWindow(arg1, arg2) {
  return window['go']['main']['App']['OpenEMLWindow'](arg1, arg2);
}

export function OpenImage(arg1, arg2) {
  return window['go']['main']['App']['OpenImage'](arg1, arg2);
}

export function OpenImageWindow(arg1, arg2) {
  return window['go']['main']['App']['OpenImageWindow'](arg1, arg2);
}

export function OpenPDF(arg1, arg2) {
  return window['go']['main']['App']['OpenPDF'](arg1, arg2);
}

export function OpenPDFWindow(arg1, arg2) {
  return window['go']['main']['App']['OpenPDFWindow'](arg1, arg2);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadEML(arg1) {
  return window['go']['main']['App']['ReadEML'](arg1);
}

export function ReadMSG(arg1, arg2) {
  return window['go']['main']['App']['ReadMSG'](arg1, arg2);
}

export function ReadMSGOSS(arg1) {
  return window['go']['main']['App']['ReadMSGOSS'](arg1);
}

export function ReadPEC(arg1) {
  return window['go']['main']['App']['ReadPEC'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowOpenFileDialog() {
  return window['go']['main']['App']['ShowOpenFileDialog']();
}
