// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIsDefaultEMLHandler() {
  return ObfuscatedCall(0, []);
}

export function GetConfig() {
  return ObfuscatedCall(1, []);
}

export function GetImageViewerData() {
  return ObfuscatedCall(2, []);
}

export function GetMachineData() {
  return ObfuscatedCall(3, []);
}

export function GetPDFViewerData() {
  return ObfuscatedCall(4, []);
}

export function GetStartupFile() {
  return ObfuscatedCall(5, []);
}

export function GetViewerData() {
  return ObfuscatedCall(6, []);
}

export function IsDebuggerRunning() {
  return ObfuscatedCall(7, []);
}

export function OpenDefaultAppsSettings() {
  return ObfuscatedCall(8, []);
}

export function OpenEMLWindow(arg1, arg2) {
  return ObfuscatedCall(9, [arg1, arg2]);
}

export function OpenImage(arg1, arg2) {
  return ObfuscatedCall(10, [arg1, arg2]);
}

export function OpenImageWindow(arg1, arg2) {
  return ObfuscatedCall(11, [arg1, arg2]);
}

export function OpenPDF(arg1, arg2) {
  return ObfuscatedCall(12, [arg1, arg2]);
}

export function OpenPDFWindow(arg1, arg2) {
  return ObfuscatedCall(13, [arg1, arg2]);
}

export function QuitApp() {
  return ObfuscatedCall(14, []);
}

export function ReadEML(arg1) {
  return ObfuscatedCall(15, [arg1]);
}

export function ReadMSG(arg1, arg2) {
  return ObfuscatedCall(16, [arg1, arg2]);
}

export function ReadMSGOSS(arg1) {
  return ObfuscatedCall(17, [arg1]);
}

export function ReadPEC(arg1) {
  return ObfuscatedCall(18, [arg1]);
}

export function SaveConfig(arg1) {
  return ObfuscatedCall(19, [arg1]);
}

export function ShowOpenFileDialog() {
  return ObfuscatedCall(20, []);
}
